
[window]

opacity = 0.85

padding.x = 10
padding.y = 10

decorations = "Full"
decorations_theme_variant = "Light" # "Dark"

[font]

normal.family = "Hack"
bold.family = "Hack"
italic.family = "Hack"
bold_italic.family = "Hack"

size = 5.0

[colors.primary]
background = "0x141b1e"
foreground = "0xd3c6aa"

[colors.normal]
black   = "0x232a2d"
red     = "0xe57474"
green   = "0x8ccf7e"
yellow  = "0xe5c76b"
blue    = "0x67b0e8"
magenta = "0xc47fd5"
cyan    = "0x6cbfbf"
white   = "0xd3c6aa"

[colors.bright]
black   = "0x2d3437"
red     = "0xef7d7d"
green   = "0x9bdead"
yellow  = "0xf1cf8a"
blue    = "0x71baf2"
magenta = "0xce89df"
cyan    = "0x67cbe7"
white   = "0xe4e1cd"
